import { Restaurant } from '@src/types';

export const test = 1;

export const restaurants: Restaurant = {
  'China Taste': {
    address: '1234 Sheridan Drive',
    fee: 1,
    time: '15-20 min',
    category: 'Chinese, Asian',
    id: 1,
    reviewCount: 0,
    image: '/imgs/restaurant-hero-holder.jpg',
    mile: 1.5,
  },
  'India Taste': {
    address: '12345 Sheridan Drive',
    fee: 1,
    time: '15-20 min',
    category: 'India, Asian',
    id: 2,
    reviewCount: 0,
    image: '/imgs/restaurant-hero-holder-2.jpg',
    mile: 1.1,
  },
  MDonald: {
    address: '1233 Sheridan Drive',
    fee: 1,
    time: '15-20 min',
    category: 'Fast Food',
    id: 3,
    reviewCount: 0,
    image: '/imgs/restaurant-hero-holder-3.jpg',
    mile: 1.2,
  },
  'Taco Dell': {
    address: '12234 Sheridan Drive',
    fee: 1,
    time: '15-20 min',
    category: 'Taco',
    id: 4,
    reviewCount: 0,
    image: '/imgs/restaurant-hero-holder.jpg',
    mile: 1.3,
  },
  Starb: {
    address: '123445 Sheridan Drive',
    fee: 1,
    time: '15-20 min',
    category: 'Drink',
    id: 5,
    reviewCount: 0,
    image: '/imgs/restaurant-hero-holder-2.jpg',
    mile: 1.4,
  },
  'Test 1': {
    address: '123445 Sheridan Drive',
    fee: 1,
    time: '15-20 min',
    category: 'Test Category',
    id: 6,
    reviewCount: 0,
    image: '/imgs/restaurant-hero-holder-2.jpg',
    mile: 1.5,
  },
  'Test 2': {
    address: '123445 Sheridan Drive',
    fee: 1,
    time: '15-20 min',
    category: 'Test Category 2',
    id: 7,
    reviewCount: 0,
    image: '/imgs/restaurant-hero-holder-2.jpg',
    mile: 1.6,
  },
};

export const topRestaurants: Restaurant = {
  'China Taste': {
    address: '1234 Sheridan Drive',
    fee: 1,
    time: '15-20 min',
    category: 'Chinese, Asian',
    id: 1,
    reviewCount: 0,
    image: '/imgs/restaurant-hero-holder.jpg',
    mile: 1.1,
  },
  'India Taste': {
    address: '12345 Sheridan Drive',
    fee: 1,
    time: '15-20 min',
    category: 'India, Asian',
    id: 2,
    reviewCount: 0,
    image: '/imgs/restaurant-hero-holder-2.jpg',
    mile: 1.2,
  },
  MDonald: {
    address: '1233 Sheridan Drive',
    fee: 1,
    time: '15-20 min',
    category: 'Fast Food',
    id: 3,
    reviewCount: 0,
    image: '/imgs/restaurant-hero-holder-3.jpg',
    mile: 1.3,
  },
  'Taco Dell': {
    address: '12234 Sheridan Drive',
    fee: 1,
    time: '15-20 min',
    category: 'Taco',
    id: 4,
    reviewCount: 0,
    image: '/imgs/restaurant-hero-holder.jpg',
    mile: 1.4,
  },
  'China India America Random Taste': {
    address: '123445 Sheridan Drive',
    fee: 1,
    time: '15-20 min',
    category: 'Drink',
    id: 5,
    reviewCount: 0,
    image: '/imgs/restaurant-hero-holder-2.jpg',
    mile: 1.5,
  },
};
